# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1804"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/code"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    echo ">>>>> Installing Python <<<<<"
    sudo apt-get install python2.7 python-pip -y
    echo ""
    echo ">>>>> Python is installed <<<<<"
    python --version
    echo ">>>>> Installing Java <<<<<"
    sudo apt-get install openjdk-8-jdk -y
    echo ">>>>> Java is installed <<<<"
    java --versiongit
    echo ">>>>> Installing Apache Casandra <<<<<"
    echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
    curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install cassandra -y
    echo "Booting up Casandra"
    sudo service cassandra start
  SHELL
end
